name: ODBC Scanner
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  DUCKDB_CAPI_LIB_URL_LINUX_AMD64: https://github.com/duckdb/duckdb/releases/latest/download/libduckdb-linux-amd64.zip
  CCACHE_DIR: ${{ github.workspace }}/ccache

jobs:
  format-check:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: |
          python -m pip install --user clang_format==11.0.1
          python ./resources/scripts/format.py --check 

  duckdb-linux-amd64:
    name: DuckDB Linux (amd64)
    runs-on: ubuntu-latest
    needs: format-check
    env:
      GEN: ninja
      CC: 'ccache gcc'
      CXX: 'ccache g++'
      ODBC_CONN_STRING: Driver={DuckDB Driver};
      DUCKDB_ODBC_LIB_URL: https://github.com/duckdb/duckdb-odbc/releases/latest/download/duckdb_odbc-linux-amd64.zip
      DUCKDB_ODBC_LIB_PATH: ${{ github.workspace }}/odbc/libduckdb_odbc.so
      DUCKDB_CAPI_LIB_PATH: ${{ github.workspace }}/libduckdb/libduckdb.so
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Dependencies
        run: |
          echo "set man-db/auto-update false" | sudo debconf-communicate
          sudo dpkg-reconfigure man-db
          sudo apt-get update -y -q -o=Dpkg::Use-Pty=0
          sudo apt-get install -y -q -o=Dpkg::Use-Pty=0 \
            ccache \
            ninja-build \
            python3-pyodbc \
            unixodbc-dev

      - name: DuckDB ODBC Lib
        run: |
          mkdir odbc
          pushd odbc
          curl --no-progress-meter -LO "${DUCKDB_ODBC_LIB_URL}"
          unzip -q duckdb_odbc-linux-amd64.zip
          ls -laR
          popd
          ./resources/scripts/write_odbcinst_ini.sh DuckDB "${DUCKDB_ODBC_LIB_PATH}"
          python ./resources/scripts/pyodbc_version.py --dbms DuckDB --conn-str "${ODBC_CONN_STRING}"

      - name: DuckDB CAPI Lib
        run: |
          mkdir libduckdb
          cd libduckdb
          curl --no-progress-meter -LO ${DUCKDB_CAPI_LIB_URL_LINUX_AMD64}
          unzip -q libduckdb-linux-amd64.zip
          ls -laR

      - name: Build
        run: |
          make configure
          make release

      - name: C API Tests
        run: |
          make test

      - name: SQL Tests
        run: |
          python ./resources/scripts/run_sqllogic_tests.py --dbms DuckDB

      - name: Save Cache
        uses: actions/cache/save@v5
        with:
          path: ${{ github.workspace }}/ccache
          key: ${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}

  duckdb-osx-aarch64:
    name: DuckDB MacOS (aarch64)
    runs-on: macos-latest
    needs: duckdb-linux-amd64
    env:
      GEN: ninja
      ODBC_CONN_STRING: Driver={DuckDB Driver};
      DUCKDB_ODBC_LIB_URL: https://github.com/duckdb/duckdb-odbc/releases/latest/download/duckdb_odbc-osx-universal.zip
      DUCKDB_ODBC_LIB_PATH: ${{ github.workspace }}/odbc/libduckdb_odbc.dylib
      DUCKDB_CAPI_LIB_URL: https://github.com/duckdb/duckdb/releases/latest/download/libduckdb-osx-universal.zip
      DUCKDB_CAPI_LIB_PATH: ${{ github.workspace }}/libduckdb/libduckdb.dylib
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Dependencies
        run: |
          brew install -q \
            ninja \
            unixodbc

      - name: Configure
        run: |
          make configure

      - name: DuckDB ODBC Lib
        run: |
          mkdir odbc
          pushd odbc
          curl --no-progress-meter -LO "${DUCKDB_ODBC_LIB_URL}"
          unzip -q duckdb_odbc-osx-universal.zip
          ls -laR
          popd
          ./resources/scripts/macos_update_downloaded_lib.sh ${DUCKDB_ODBC_LIB_PATH}
          ./resources/scripts/write_odbcinst_ini.sh DuckDB "${DUCKDB_ODBC_LIB_PATH}"
          ./configure/venv/bin/python -m pip install pyodbc
          ./configure/venv/bin/python ./resources/scripts/pyodbc_version.py --dbms DuckDB --conn-str "${ODBC_CONN_STRING}"

      - name: DuckDB CAPI Lib
        run: |
          mkdir libduckdb
          pushd libduckdb
          curl --no-progress-meter -LO "${DUCKDB_CAPI_LIB_URL}"
          unzip -q libduckdb-osx-universal.zip
          ls -laR
          popd

      - name: Build
        run: |
          make release

      - name: C API Tests
        run: |
          make test

      - name: SQL Tests
        run: |
          ./configure/venv/bin/python ./resources/scripts/run_sqllogic_tests.py --dbms DuckDB

  duckdb-windows-amd64:
    name: DuckDB Windows (amd64)
    runs-on: windows-latest
    needs: duckdb-linux-amd64
    env:
      GEN: ninja
      CC: 'ccache cl'
      CXX: 'ccache cl'
      CCACHE_DIR: ${{ github.workspace }}/ccache
      ODBC_CONN_STRING: Driver={DuckDB Driver};
      DUCKDB_ODBC_LIB_URL: https://github.com/duckdb/duckdb-odbc/releases/latest/download/duckdb_odbc-windows-amd64.zip
      DUCKDB_CAPI_LIB_URL: https://github.com/duckdb/duckdb/releases/latest/download/libduckdb-windows-amd64.zip
      DUCKDB_CAPI_LIB_PATH: ${{ github.workspace }}/libduckdb/duckdb.lib
      DUCKDB_CAPI_LIB_SHARED_PATH: ${{ github.workspace }}/libduckdb/duckdb.dll
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Dependencies
        shell: bash
        run: |
          choco install \
            ccache \
            curl \
            unzip \
            --no-progress

      - name: Configure
        shell: bash
        run: |
          make configure

      - name: DuckDB ODBC Lib
        shell: bash
        run: |
          mkdir odbc
          pushd odbc
          curl --no-progress-meter -LO "${DUCKDB_ODBC_LIB_URL}"
          unzip -q duckdb_odbc-windows-amd64.zip
          ls -laR
          ./odbc_install.exe //CI //Install
          popd
          ./configure/venv/Scripts/python.exe -m pip install pyodbc
          ./configure/venv/Scripts/python.exe ./resources/scripts/pyodbc_version.py --dbms DuckDB --conn-str "${ODBC_CONN_STRING}"

      - name: DuckDB CAPI Lib
        shell: bash
        run: |
          mkdir libduckdb
          pushd libduckdb
          curl --no-progress-meter -LO "${DUCKDB_CAPI_LIB_URL}"
          unzip -q libduckdb-windows-amd64.zip
          ls -laR
          popd

      - name: Build
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\18\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          del "C:\Program Files\Git\usr\bin\link.exe"
          bash -c "make release"

      - name: List Symbols
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\18\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          dumpbin.exe /imports build\release\odbc_scanner.duckdb_extension
          dumpbin.exe /exports build\release\odbc_scanner.duckdb_extension

      - name: C API Tests
        shell: bash
        run: |
          cp "${DUCKDB_CAPI_LIB_SHARED_PATH}" ./cmake_build/release/test/
          make test

      - name: SQL Tests
        shell: bash
        run: |
          ./configure/venv/Scripts/python.exe ./resources/scripts/run_sqllogic_tests.py --dbms DuckDB

      - name: Save Cache
        uses: actions/cache/save@v5
        with:
          path: ${{ github.workspace }}/ccache
          key: ${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}

  mssql-linux-amd64:
    name: MSSQL Linux (amd64)
    runs-on: ubuntu-latest
    needs: duckdb-linux-amd64
    env:
      GEN: ninja
      CC: 'ccache gcc'
      CXX: 'ccache g++'
      ODBC_CONN_STRING: Driver={MSSQL Driver};Server=tcp:127.0.0.1,1433;UID=sa;PWD=P@ssword2;TrustServerCertificate=yes;
      DUCKDB_CAPI_LIB_PATH: ${{ github.workspace }}/libduckdb/libduckdb.so
      MSSQL_ODBC_LIB_PATH: /opt/microsoft/msodbcsql18/lib64/libmsodbcsql-18.6.so.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Restore Cache
        uses: actions/cache/restore@v5
        with:
          path: ${{ github.workspace }}/ccache
          key: ${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}

      - name: Dependencies
        run: |
          echo "set man-db/auto-update false" | sudo debconf-communicate
          sudo dpkg-reconfigure man-db
          sudo apt-get update -y -q -o=Dpkg::Use-Pty=0
          sudo apt-get install -y -q -o=Dpkg::Use-Pty=0 \
            ccache \
            ninja-build \
            python3-pyodbc \
            unixodbc-dev

      - name: MSSQL Server
        env:
          ACCEPT_EULA: 1
          MSSQL_SA_PASSWORD: P@ssword2
          MSSQL_PID: Developer
          MSSQL_IP_ADDRESS: 127.0.0.1
          MSSQL_TCP_PORT: 1433
        run: |
          curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --batch --yes --dearmor -o /usr/share/keyrings/microsoft-prod.gpg
          curl -sSL https://packages.microsoft.com/config/ubuntu/24.04/mssql-server-preview.list | sudo tee /etc/apt/sources.list.d/mssql-server-preview.list
          sudo apt-get update -y -q -o=Dpkg::Use-Pty=0
          sudo apt-get install -y -q -o=Dpkg::Use-Pty=0 \
            mssql-server
          sudo -E /opt/mssql/bin/mssql-conf -n setup
          systemctl status mssql-server

      - name: MSSQL ODBC Lib
        run: |
          curl -sSL -O https://packages.microsoft.com/config/ubuntu/24.04/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update -y -q -o=Dpkg::Use-Pty=0
          sudo apt-get install -y -q -o=Dpkg::Use-Pty=0 \
            msodbcsql18
          cat /etc/odbcinst.ini
          ldd "${MSSQL_ODBC_LIB_PATH}"
          ./resources/scripts/write_odbcinst_ini.sh MSSQL "${MSSQL_ODBC_LIB_PATH}"
          python ./resources/scripts/pyodbc_version.py --dbms MSSQL --conn-str "${ODBC_CONN_STRING}"

      - name: DuckDB CAPI Lib
        run: |
          mkdir libduckdb
          cd libduckdb
          curl --no-progress-meter -LO ${DUCKDB_CAPI_LIB_URL_LINUX_AMD64}
          unzip -q libduckdb-linux-amd64.zip
          ls -laR

      - name: Build
        run: |
          make configure
          make release

      - name: C API Tests
        run: |
          make test

      - name: SQL Tests
        run: |
          python ./resources/scripts/run_sqllogic_tests.py --dbms MSSQL

  postgres-linux-amd64:
    name: PostgreSQL Linux (amd64)
    runs-on: ubuntu-latest
    needs: duckdb-linux-amd64
    env:
      GEN: ninja
      CC: 'ccache gcc'
      CXX: 'ccache g++'
      ODBC_CONN_STRING: Driver={PostgreSQL Driver};Server=127.0.0.1;Port:1433;Username=postgres;Password=postgres;
      DUCKDB_CAPI_LIB_PATH: ${{ github.workspace }}/libduckdb/libduckdb.so
      POSTGRES_ODBC_LIB_PATH: /usr/lib/x86_64-linux-gnu/odbc/psqlodbcw.so
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Restore Cache
        uses: actions/cache/restore@v5
        with:
          path: ${{ github.workspace }}/ccache
          key: ${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}

      - name: Dependencies
        run: |
          echo "set man-db/auto-update false" | sudo debconf-communicate
          sudo dpkg-reconfigure man-db
          sudo apt-get update -y -q -o=Dpkg::Use-Pty=0
          sudo apt-get install -y -q -o=Dpkg::Use-Pty=0 \
            ccache \
            ninja-build \
            python3-pyodbc \
            unixodbc-dev

      - name: PostgreSQL Server
        run: |
          sudo systemctl start postgresql
          sudo systemctl status postgresql
          sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'postgres'"

      - name: PostgreSQL ODBC Lib
        run: |
          sudo apt-get install -y -q -o=Dpkg::Use-Pty=0 \
            odbc-postgresql
          cat /etc/odbcinst.ini
          ldd "${POSTGRES_ODBC_LIB_PATH}"
          ./resources/scripts/write_odbcinst_ini.sh PostgreSQL "${POSTGRES_ODBC_LIB_PATH}"
          python ./resources/scripts/pyodbc_version.py --dbms PostgreSQL --conn-str "${ODBC_CONN_STRING}"

      - name: DuckDB CAPI Lib
        run: |
          mkdir libduckdb
          cd libduckdb
          curl --no-progress-meter -LO ${DUCKDB_CAPI_LIB_URL_LINUX_AMD64}
          unzip -q libduckdb-linux-amd64.zip
          ls -laR

      - name: Build
        run: |
          make configure
          make release

      - name: C API Tests
        run: |
          make test

      - name: SQL Tests
        run: |
          python ./resources/scripts/run_sqllogic_tests.py --dbms Postgres

  mariadb-linux-amd64:
    name: MariaDB Linux (amd64)
    runs-on: ubuntu-latest
    needs: duckdb-linux-amd64
    env:
      GEN: ninja
      CC: 'ccache gcc'
      CXX: 'ccache g++'
      ODBC_CONN_STRING: Driver={MariaDB Driver};SERVER=127.0.0.1;PORT=3306;USER=root;PASSWORD=root;
      DUCKDB_CAPI_LIB_PATH: ${{ github.workspace }}/libduckdb/libduckdb.so
      MARIADB_ODBC_LIB_PATH: /usr/lib/x86_64-linux-gnu/odbc/libmaodbc.so
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Restore Cache
        uses: actions/cache/restore@v5
        with:
          path: ${{ github.workspace }}/ccache
          key: ${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}

      - name: Dependencies
        run: |
          echo "set man-db/auto-update false" | sudo debconf-communicate
          sudo dpkg-reconfigure man-db
          sudo apt-get update -y -q -o=Dpkg::Use-Pty=0
          sudo apt-get install -y -q -o=Dpkg::Use-Pty=0 \
            ccache \
            ninja-build \
            python3-pyodbc \
            unixodbc-dev

      - name: MariaDB Server
        run: |
          sudo apt-get install -y -q -o=Dpkg::Use-Pty=0 \
            mariadb-server 
          sudo systemctl start mariadb
          sudo systemctl status mariadb
          sudo mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'root';"

      - name: MariaDB ODBC Lib
        run: |
          sudo apt-get install -y -q -o=Dpkg::Use-Pty=0 \
            odbc-mariadb
          cat /etc/odbcinst.ini
          ldd "${MARIADB_ODBC_LIB_PATH}"
          ./resources/scripts/write_odbcinst_ini.sh MariaDB "${MARIADB_ODBC_LIB_PATH}"
          python ./resources/scripts/pyodbc_version.py --dbms MariaDB --conn-str "${ODBC_CONN_STRING}"

      - name: DuckDB CAPI Lib
        run: |
          mkdir libduckdb
          cd libduckdb
          curl --no-progress-meter -LO ${DUCKDB_CAPI_LIB_URL_LINUX_AMD64}
          unzip -q libduckdb-linux-amd64.zip
          ls -laR

      - name: Build
        run: |
          make configure
          make release

      - name: C API Tests
        run: |
          make test

      - name: SQL Tests
        run: |
          python ./resources/scripts/run_sqllogic_tests.py --dbms MySQL

  mysql-linux-amd64:
    name: MySQL Linux (amd64)
    runs-on: ubuntu-latest
    needs: duckdb-linux-amd64
    env:
      GEN: ninja
      CC: 'ccache gcc'
      CXX: 'ccache g++'
      ODBC_CONN_STRING: Driver={MySQL Driver};SERVER=127.0.0.1;PORT=3306;USER=root;PASSWORD=root;
      DUCKDB_CAPI_LIB_PATH: ${{ github.workspace }}/libduckdb/libduckdb.so
      MYSQL_ODBC_LIB_URL: https://github.com/staticlibs/odbclibs_tmp/releases/download/tmp1/mysql_odbc_9.4.0_ubuntu_24.04_amd64.tar.xz
      MYSQL_ODBC_LIB_PATH: ${{ github.workspace }}/mysql_odbc_9.4.0_ubuntu_24.04_amd64/lib/libmyodbc9w.so
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Restore Cache
        uses: actions/cache/restore@v5
        with:
          path: ${{ github.workspace }}/ccache
          key: ${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}

      - name: Dependencies
        run: |
          echo "set man-db/auto-update false" | sudo debconf-communicate
          sudo dpkg-reconfigure man-db
          sudo apt-get update -y -q -o=Dpkg::Use-Pty=0
          sudo apt-get install -y -q -o=Dpkg::Use-Pty=0 \
            ccache \
            ninja-build \
            python3-pyodbc \
            unixodbc-dev

      - name: MySQL Server
        run: |
          sudo systemctl start mysql
          sudo systemctl status mysql
          # sudo mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'root';"
          
      - name: MySQL ODBC Lib
        run: |
          curl --no-progress-meter -LO "${MYSQL_ODBC_LIB_URL}"
          tar xJvf mysql_odbc_9.4.0_ubuntu_24.04_amd64.tar.xz
          ldd "${MYSQL_ODBC_LIB_PATH}"
          ./resources/scripts/write_odbcinst_ini.sh MySQL "${MYSQL_ODBC_LIB_PATH}"
          python ./resources/scripts/pyodbc_version.py --dbms MySQL --conn-str "${ODBC_CONN_STRING}"

      - name: DuckDB CAPI Lib
        run: |
          mkdir libduckdb
          cd libduckdb
          curl --no-progress-meter -LO ${DUCKDB_CAPI_LIB_URL_LINUX_AMD64}
          unzip -q libduckdb-linux-amd64.zip
          ls -laR

      - name: Build
        run: |
          make configure
          make release

      - name: C API Tests
        run: |
          make test

      - name: SQL Tests
        run: |
          python ./resources/scripts/run_sqllogic_tests.py --dbms MySQL

  oracle-linux-amd64:
    name: Oracle Linux (amd64)
    runs-on: ubuntu-latest
    needs: duckdb-linux-amd64
    env:
      GEN: ninja
      CC: 'ccache gcc'
      CXX: 'ccache g++'
      ODBC_CONN_STRING: Driver={Oracle Driver};DBQ=//127.0.0.1:1521/XE;UID=system;PWD=tiger;
      DUCKDB_CAPI_LIB_PATH: ${{ github.workspace }}/libduckdb/libduckdb.so
      ORACLE_ODBC_LIB_URL1: https://download.oracle.com/otn_software/linux/instantclient/2326000/instantclient-basiclite-linux.x64-23.26.0.0.0.zip
      ORACLE_ODBC_LIB_URL2: https://download.oracle.com/otn_software/linux/instantclient/2326000/instantclient-odbc-linux.x64-23.26.0.0.0.zip
      ORACLE_ODBC_LIB_PATH: ${{ github.workspace }}/instantclient_23_26/libsqora.so.23.1
      LD_LIBRARY_PATH: ${{ github.workspace }}/instantclient_23_26/
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Restore Cache
        uses: actions/cache/restore@v5
        with:
          path: ${{ github.workspace }}/ccache
          key: ${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}

      - name: Dependencies
        run: |
          echo "set man-db/auto-update false" | sudo debconf-communicate
          sudo dpkg-reconfigure man-db
          sudo apt-get update -y -q -o=Dpkg::Use-Pty=0
          sudo apt-get install -y -q -o=Dpkg::Use-Pty=0 \
            ccache \
            ninja-build \
            python3-pyodbc \
            unixodbc-dev

      - name: Oracle Docker 
        run: |
          docker run -id      \
          --name oracle       \
          -p 1521:1521        \
          -e ORACLE_PWD=tiger \
          container-registry.oracle.com/database/express

      - name: Oracle ODBC Lib
        run: |
          sudo apt-get install -y -q -o=Dpkg::Use-Pty=0 \
            libaio1t64
          curl --no-progress-meter -LO "${ORACLE_ODBC_LIB_URL1}"
          unzip instantclient-basiclite-linux.x64-23.26.0.0.0.zip
          curl --no-progress-meter -LO  "${ORACLE_ODBC_LIB_URL2}"
          unzip -o instantclient-odbc-linux.x64-23.26.0.0.0.zip
          pushd ${{ github.workspace }}/instantclient_23_26/
          ln -s /usr/lib/x86_64-linux-gnu/libaio.so.1t64.0.2 libaio.so.1
          popd
          ldd "${ORACLE_ODBC_LIB_PATH}"
          ./resources/scripts/write_odbcinst_ini.sh Oracle "${ORACLE_ODBC_LIB_PATH}"
          python ./resources/scripts/pyodbc_version.py --dbms Oracle --conn-str "${ODBC_CONN_STRING}"

      - name: DuckDB CAPI Lib
        run: |
          mkdir libduckdb
          cd libduckdb
          curl --no-progress-meter -LO ${DUCKDB_CAPI_LIB_URL_LINUX_AMD64}
          unzip -q libduckdb-linux-amd64.zip
          ls -laR

      - name: Build
        run: |
          make configure
          make release

      - name: C API Tests
        run: |
          make test

      - name: SQL Tests
        run: |
          python ./resources/scripts/run_sqllogic_tests.py --dbms Oracle

  db2-linux-amd64:
    name: DB2 Linux (amd64)
    runs-on: ubuntu-latest
    needs: duckdb-linux-amd64
    env:
      GEN: ninja
      CC: 'ccache gcc'
      CXX: 'ccache g++'
      DUCKDB_CAPI_LIB_PATH: ${{ github.workspace }}/libduckdb/libduckdb.so
      ODBC_CONN_STRING: Driver={DB2 Driver};HostName=127.0.0.1;Port=50000;Database=testdb;UID=db2inst1;PWD=testpwd;
      DB2_ODBC_LIB_URL: https://github.com/staticlibs/odbclibs_tmp/releases/download/tmp1/v12.1.2_linuxx64_odbc_cli.tar.gz
      DB2_ODBC_LIB_PATH: ${{ github.workspace }}/odbc_cli/clidriver/lib/libdb2o.so
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Restore Cache
        uses: actions/cache/restore@v5
        with:
          path: ${{ github.workspace }}/ccache
          key: ${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}

      - name: Dependencies
        run: |
          echo "set man-db/auto-update false" | sudo debconf-communicate
          sudo dpkg-reconfigure man-db
          sudo apt-get update -y -q -o=Dpkg::Use-Pty=0
          sudo apt-get install -y -q -o=Dpkg::Use-Pty=0 \
            ccache \
            ninja-build \
            python3-pyodbc \
            unixodbc-dev

      - name: DB2 Docker
        run: |
          mkdir db2_data
          docker run -id                                 \
          --privileged=true                              \
          --name db2                                     \
          -p 50000:50000                                 \
          -e LICENSE=accept                              \
          -e DB2INST1_PASSWORD=testpwd                   \
          -e DBNAME=testdb                               \
          -v ${{ github.workspace }}/db2_data/:/database \
           icr.io/db2_community/db2

      - name: DB2 ODBC Lib
        run: |
          curl --no-progress-meter -LO "${DB2_ODBC_LIB_URL}"
          tar xzvf v12.1.2_linuxx64_odbc_cli.tar.gz
          ldd "${DB2_ODBC_LIB_PATH}"
          ./resources/scripts/write_odbcinst_ini.sh DB2 "${DB2_ODBC_LIB_PATH}"
          python ./resources/scripts/pyodbc_version.py --dbms DB2 --conn-str "${ODBC_CONN_STRING}"
          # The DB instance in container is auto-restarted after initialization, 
          # so we sleep for a bit and check the connection again
          sleep 15
          python ./resources/scripts/pyodbc_version.py --dbms DB2 --conn-str "${ODBC_CONN_STRING}"

      - name: DuckDB CAPI Lib
        run: |
          mkdir libduckdb
          cd libduckdb
          curl --no-progress-meter -LO ${DUCKDB_CAPI_LIB_URL_LINUX_AMD64}
          unzip -q libduckdb-linux-amd64.zip
          ls -laR

      - name: Build
        run: |
          make configure
          make release

      - name: C API Tests
        run: |
          make test

      - name: SQL Tests
        run: |
          python ./resources/scripts/run_sqllogic_tests.py --dbms DB2

  clickhouse-linux-amd64:
    name: ClickHouse Linux (amd64)
    runs-on: ubuntu-latest
    needs: duckdb-linux-amd64
    env:
      GEN: ninja
      CC: 'ccache gcc'
      CXX: 'ccache g++'
      ODBC_CONN_STRING: Driver={ClickHouse Driver};Server=127.0.0.1;Port=8123;
      DUCKDB_CAPI_LIB_PATH: ${{ github.workspace }}/libduckdb/libduckdb.so
      CLICKHOUSE_ODBC_LIB_URL: https://github.com/ClickHouse/clickhouse-odbc/releases/download/1.4.3.20250807/clickhouse-odbc-linux-Clang-UnixODBC-Release.zip
      CLICKHOUSE_ODBC_LIB_PATH: ${{ github.workspace }}/clickhouse-odbc-1.4.3-Linux/lib/libclickhouseodbcw.so
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Restore Cache
        uses: actions/cache/restore@v5
        with:
          path: ${{ github.workspace }}/ccache
          key: ${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}

      - name: Dependencies
        run: |
          echo "set man-db/auto-update false" | sudo debconf-communicate
          sudo dpkg-reconfigure man-db
          sudo apt-get update -y -q -o=Dpkg::Use-Pty=0
          sudo apt-get install -y -q -o=Dpkg::Use-Pty=0 \
            ccache \
            ninja-build \
            python3-pyodbc \
            unixodbc-dev

      - name: ClickHouse Server
        run: |
          curl --no-progress-meter -fsSL 'https://packages.clickhouse.com/rpm/stable/repodata/repomd.xml.key' | sudo gpg --dearmor -o /usr/share/keyrings/clickhouse-keyring.gpg
          ARCH=$(dpkg --print-architecture)
          echo "deb [signed-by=/usr/share/keyrings/clickhouse-keyring.gpg arch=${ARCH}] https://packages.clickhouse.com/deb stable main" | sudo tee /etc/apt/sources.list.d/clickhouse.list
          sudo apt-get update -y -q -o=Dpkg::Use-Pty=0
          sudo apt-get install -y -q -o=Dpkg::Use-Pty=0 \
            clickhouse-server
          sudo systemctl start clickhouse-server
          sudo systemctl status clickhouse-server
          
      - name: ClickHouse ODBC Lib
        run: |
          curl --no-progress-meter -LO "${CLICKHOUSE_ODBC_LIB_URL}"
          unzip clickhouse-odbc-linux-Clang-UnixODBC-Release.zip
          tar xJvf clickhouse-odbc-1.4.3-Linux.tar.xz
          ldd "${CLICKHOUSE_ODBC_LIB_PATH}"
          ./resources/scripts/write_odbcinst_ini.sh ClickHouse "${CLICKHOUSE_ODBC_LIB_PATH}"
          python ./resources/scripts/pyodbc_version.py --dbms ClickHouse --conn-str "${ODBC_CONN_STRING}"

      - name: DuckDB CAPI Lib
        run: |
          mkdir libduckdb
          cd libduckdb
          curl --no-progress-meter -LO ${DUCKDB_CAPI_LIB_URL_LINUX_AMD64}
          unzip -q libduckdb-linux-amd64.zip
          ls -laR

      - name: Build
        run: |
          make configure
          make release

      - name: C API Tests
        run: |
          make test

      - name: SQL Tests
        run: |
          python ./resources/scripts/run_sqllogic_tests.py --dbms ClickHouse

  spark-linux-amd64:
    name: Spark Linux (amd64)
    runs-on: ubuntu-latest
    needs: duckdb-linux-amd64
    env:
      GEN: ninja
      CC: 'ccache gcc'
      CXX: 'ccache g++'
      ODBC_CONN_STRING: Driver={Spark Driver};Host=127.0.0.1;Port=10000;
      DUCKDB_CAPI_LIB_PATH: ${{ github.workspace }}/libduckdb/libduckdb.so
      SPARK_SERVER_URL: https://blobs.duckdb.org/ci/spark-3.5.3-bin-hadoop3.tgz
      SPARK_ODBC_LIB_URL: https://databricks-bi-artifacts.s3.us-east-2.amazonaws.com/simbaspark-drivers/odbc/2.9.2/SimbaSparkODBC-2.9.2.1008-Debian-64bit.zip
      SPARK_ODBC_LIB_PATH: /opt/simba/spark/lib/64/libsparkodbc_sb64.so
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Restore Cache
        uses: actions/cache/restore@v5
        with:
          path: ${{ github.workspace }}/ccache
          key: ${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}

      - name: Dependencies
        run: |
          echo "set man-db/auto-update false" | sudo debconf-communicate
          sudo dpkg-reconfigure man-db
          sudo apt-get update -y -q -o=Dpkg::Use-Pty=0
          sudo apt-get install -y -q -o=Dpkg::Use-Pty=0 \
            ccache \
            ninja-build \
            python3-pyodbc \
            unixodbc-dev

      - name: Spark Thrift Server
        run: |
          curl --no-progress-meter -LO "${SPARK_SERVER_URL}"
          tar xf spark-3.5.3-bin-hadoop3.tgz
          cd spark-3.5.3-bin-hadoop3
          ./sbin/start-thriftserver.sh
          
      - name: Spark ODBC Lib
        run: |
          curl --no-progress-meter -LO "${SPARK_ODBC_LIB_URL}"
          unzip SimbaSparkODBC-2.9.2.1008-Debian-64bit.zip
          sudo apt-get install -y -q -o=Dpkg::Use-Pty=0 \
            ./SimbaSparkODBC-2.9.2.1008-Debian-64bit/simbaspark_2.9.2.1008-2_amd64.deb
          ldd "${SPARK_ODBC_LIB_PATH}"
          ./resources/scripts/write_odbcinst_ini.sh Spark "${SPARK_ODBC_LIB_PATH}"
          python ./resources/scripts/pyodbc_version.py --dbms Spark --conn-str "${ODBC_CONN_STRING}"

      - name: DuckDB CAPI Lib
        run: |
          mkdir libduckdb
          cd libduckdb
          curl --no-progress-meter -LO ${DUCKDB_CAPI_LIB_URL_LINUX_AMD64}
          unzip -q libduckdb-linux-amd64.zip
          ls -laR

      - name: Build
        run: |
          make configure
          make release

      - name: C API Tests
        run: |
          make test

      - name: SQL Tests
        run: |
          python ./resources/scripts/run_sqllogic_tests.py --dbms Spark

  snowflake-linux-amd64:
    name: Snowflake Linux (amd64)
    if: ${{ false }}
    runs-on: ubuntu-latest
    needs: duckdb-linux-amd64
    env:
      GEN: ninja
      CC: 'ccache gcc'
      CXX: 'ccache g++'
      ODBC_CONN_STRING: Driver={Snowflake Driver};Server=${{ secrets.SNOWFLAKE_ACCOUNT_ID }}.snowflakecomputing.com;Database=SNOWFLAKE_SAMPLE_DATA;UID=${{ secrets.SNOWFLAKE_USERNAME }};PWD=${{ secrets.SNOWFLAKE_PASSWORD }};
      DUCKDB_CAPI_LIB_PATH: ${{ github.workspace }}/libduckdb/libduckdb.so
      SNOWFLAKE_ODBC_LIB_URL: https://sfc-repo.snowflakecomputing.com/odbc/linux/3.12.0/snowflake_linux_x8664_odbc-3.12.0.tgz
      SNOWFLAKE_ODBC_LIB_PATH: ${{ github.workspace }}/snowflake_odbc/lib/libSnowflake.so
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Restore Cache
        uses: actions/cache/restore@v5
        with:
          path: ${{ github.workspace }}/ccache
          key: ${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}

      - name: Dependencies
        run: |
          echo "set man-db/auto-update false" | sudo debconf-communicate
          sudo dpkg-reconfigure man-db
          sudo apt-get update -y -q -o=Dpkg::Use-Pty=0
          sudo apt-get install -y -q -o=Dpkg::Use-Pty=0 \
            ccache \
            ninja-build \
            python3-pyodbc \
            unixodbc-dev

      - name: Snowflake ODBC Lib
        run: |
          curl --no-progress-meter -LO "${SNOWFLAKE_ODBC_LIB_URL}"
          tar xzvf snowflake_linux_x8664_odbc-3.12.0.tgz
          ldd "${SNOWFLAKE_ODBC_LIB_PATH}"
          ./resources/scripts/write_odbcinst_ini.sh Snowflake "${SNOWFLAKE_ODBC_LIB_PATH}"
          python ./resources/scripts/pyodbc_version.py --dbms Snowflake --conn-str "${ODBC_CONN_STRING}"

      - name: DuckDB CAPI Lib
        run: |
          mkdir libduckdb
          cd libduckdb
          curl --no-progress-meter -LO ${DUCKDB_CAPI_LIB_URL_LINUX_AMD64}
          unzip -q libduckdb-linux-amd64.zip
          ls -laR

      - name: Build
        run: |
          make configure
          make release

      - name: C API Tests
        run: |
          make test

      - name: SQL Tests
        run: |
          python ./resources/scripts/run_sqllogic_tests.py --dbms Snowflake

  flightsql-linux-amd64:
    name: FlightSQL Linux (amd64)
    runs-on: ubuntu-latest
    needs: duckdb-linux-amd64
    env:
      GEN: ninja
      CC: 'ccache gcc'
      CXX: 'ccache g++'
      ODBC_CONN_STRING: Driver={FlightSQL Driver};Host=127.0.0.1;Port=31337;UID=gizmosql_username;PWD=gizmosql_password;useEncryption=false;
      DUCKDB_CAPI_LIB_PATH: ${{ github.workspace }}/libduckdb/libduckdb.so
      GIZMOSQL_SERVER_URL: https://github.com/gizmodata/gizmosql/releases/download/v1.12.5/gizmosql_cli_linux_amd64.zip
      FLIGHTSQL_ODBC_LIB_URL: https://github.com/staticlibs/odbclibs_tmp/releases/download/tmp1/arrow-flight-sql-odbc-driver-0.9.7.479-1.x86_64.rpm
      FLIGHTSQL_ODBC_LIB_PATH: ${{ github.workspace }}/opt/arrow-flight-sql-odbc-driver/lib64/libarrow-odbc.so.0.9.7.479
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Restore Cache
        uses: actions/cache/restore@v5
        with:
          path: ${{ github.workspace }}/ccache
          key: ${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}

      - name: Dependencies
        run: |
          echo "set man-db/auto-update false" | sudo debconf-communicate
          sudo dpkg-reconfigure man-db
          sudo apt-get update -y -q -o=Dpkg::Use-Pty=0
          sudo apt-get install -y -q -o=Dpkg::Use-Pty=0 \
            ccache \
            ninja-build \
            python3-pyodbc \
            rpm2cpio \
            unixodbc-dev

      - name: GizmoSQL Server
        env:
          GIZMOSQL_USERNAME: gizmosql_username
          GIZMOSQL_PASSWORD: gizmosql_password  
        run: |
          curl --no-progress-meter -LO "${GIZMOSQL_SERVER_URL}"
          unzip gizmosql_cli_linux_amd64.zip
          nohup ./gizmosql_server &

      - name: FlighSQL ODBC Lib
        run: |
          curl --no-progress-meter -LO "${FLIGHTSQL_ODBC_LIB_URL}"
          rpm2cpio arrow-flight-sql-odbc-driver-0.9.7.479-1.x86_64.rpm | cpio -idmv
          ldd "${FLIGHTSQL_ODBC_LIB_PATH}"
          ./resources/scripts/write_odbcinst_ini.sh FlightSQL "${FLIGHTSQL_ODBC_LIB_PATH}"
          python ./resources/scripts/pyodbc_version.py --dbms FlightSQL --conn-str "${ODBC_CONN_STRING}"

      - name: DuckDB CAPI Lib
        run: |
          mkdir libduckdb
          cd libduckdb
          curl --no-progress-meter -LO ${DUCKDB_CAPI_LIB_URL_LINUX_AMD64}
          unzip -q libduckdb-linux-amd64.zip
          ls -laR

      - name: Build
        run: |
          make configure
          make release

      - name: C API Tests
        run: |
          make test

      - name: SQL Tests
        run: |
          python ./resources/scripts/run_sqllogic_tests.py --dbms FlightSQL

  firebird-windows-amd64:
    # Note: Firebird ODBC on Linux is broken: https://github.com/FirebirdSQL/firebird-odbc-driver/pull/247 -- Use Windows for tests.
    name: Firebird Windows (amd64)
    runs-on: windows-latest
    needs: duckdb-windows-amd64
    env:
      GEN: ninja
      CC: 'ccache cl'
      CXX: 'ccache cl'
      CCACHE_DIR: ${{ github.workspace }}/ccache
      ODBC_CONN_STRING: Driver={Firebird ODBC Driver};Database=localhost:C:/tmp/test.fdb;UID=SYSDBA;PWD=masterkey;CHARSET=UTF8;
      DUCKDB_CAPI_LIB_URL: https://github.com/duckdb/duckdb/releases/latest/download/libduckdb-windows-amd64.zip
      DUCKDB_CAPI_LIB_PATH: ${{ github.workspace }}/libduckdb/duckdb.lib
      DUCKDB_CAPI_LIB_SHARED_PATH: ${{ github.workspace }}/libduckdb/duckdb.dll
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Restore Cache
        uses: actions/cache/restore@v5
        with:
          path: ${{ github.workspace }}/ccache
          key: ${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}

      - name: Dependencies
        shell: bash
        run: |
          choco install \
            ccache \
            curl \
            unzip \
            --no-progress

      - name: Configure
        shell: bash
        run: |
          make configure

      - name: Firebird Server
        shell: bash
        run: |
          choco install \
            firebird --version 5.0.3.1 \
            --no-progress
          export ISQL_EXE="C:/Program Files/Firebird/Firebird_5_0/isql.exe"
          # Initialize SYSDBA password
          echo "CREATE OR ALTER USER SYSDBA PASSWORD 'masterkey' USING PLUGIN Srp; EXIT;" | "${ISQL_EXE}" -b -user SYSDBA security.db
          # Create a test database
          mkdir "C:/tmp" 
          echo "CREATE DATABASE 'localhost:C:/tmp/test.fdb' user 'SYSDBA' password 'masterkey'; EXIT;" | "${ISQL_EXE}" -b -q

      - name: Firebird ODBC Lib
        shell: bash
        run: |
          choco install \
            firebird-odbc --version 3.0.1.21 \
            --no-progress
          ./configure/venv/Scripts/python.exe -m pip install pyodbc
          ./configure/venv/Scripts/python.exe ./resources/scripts/pyodbc_version.py --dbms Firebird --conn-str "${ODBC_CONN_STRING}"

      - name: DuckDB CAPI Lib
        shell: bash
        run: |
          mkdir libduckdb
          pushd libduckdb
          curl --no-progress-meter -LO "${DUCKDB_CAPI_LIB_URL}"
          unzip -q libduckdb-windows-amd64.zip
          ls -laR
          popd

      - name: Build
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\18\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          del "C:\Program Files\Git\usr\bin\link.exe"
          bash -c "make release"

      - name: C API Tests
        shell: bash
        run: |
          cp "${DUCKDB_CAPI_LIB_SHARED_PATH}" ./cmake_build/release/test/
          make test

      - name: SQL Tests
        shell: bash
        run: |
          ./configure/venv/Scripts/python.exe ./resources/scripts/run_sqllogic_tests.py --dbms Firebird
